name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          libjpeg-dev \
          zlib1g-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          libncurses5-dev \
          libncursesw5-dev \
          xz-utils \
          tk-dev \
          libxml2-dev \
          libxmlsec1-dev \
          libffi-dev \
          liblzma-dev \
          openjdk-8-jdk \
          git \
          unzip \
          wget \
          curl \
          cmake \
          ninja-build \
          pkg-config
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
        
    - name: Initialize buildozer
      run: |
        buildozer init
        # Update buildozer.spec with our configuration
        cp buildozer.spec buildozer.spec.backup
        
    - name: Configure buildozer for Android
      run: |
        # Set Android SDK and NDK paths
        export ANDROIDSDK="$HOME/.buildozer/android/platform/android-sdk"
        export ANDROIDNDK="$HOME/.buildozer/android/platform/android-ndk"
        export ANDROIDAPI="27"
        export ANDROIDMINAPI="21"
        
        # Create directories
        mkdir -p "$ANDROIDSDK"
        mkdir -p "$ANDROIDNDK"
        
        # Download Android SDK
        cd "$HOME/.buildozer/android/platform"
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools latest
        mkdir -p cmdline-tools
        mv latest cmdline-tools/
        
        # Set environment variables
        export ANDROID_HOME="$ANDROIDSDK"
        export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"
        
        # Accept licenses and install platform
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-27" "build-tools;27.0.3"
        
    - name: Build APK
      run: |
        export ANDROIDSDK="$HOME/.buildozer/android/platform/android-sdk"
        export ANDROIDNDK="$HOME/.buildozer/android/platform/android-ndk"
        export ANDROIDAPI="27"
        export ANDROIDMINAPI="21"
        export ANDROID_HOME="$ANDROIDSDK"
        export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"
        
        # Build the APK
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: red-kivy-app
        path: bin/*.apk
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: build-logs
        path: .buildozer/
        retention-days: 7