# Имя рабочего процесса, которое отображается на странице GitHub Actions
name: Build Android APK

# События, которые запускают этот рабочий процесс
on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при запросе на слияние в ветку main
  workflow_dispatch:  # Позволяет запускать рабочий процесс вручную

jobs:
  build:
    # Рабочий процесс будет выполняться на последней версии Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Использование действия GitHub для сборки APK с помощью Buildozer
      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.2.0
        id: buildozer
        with:
          # Команда для Buildozer: собирает отладочную версию APK
          buildozer-command: buildozer android debug
          # Версия Python для сборки (рекомендуется 3.8 для Buildozer)
          python-version: "3.8"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          # Путь к сгенерированному APK-файлу
          path: ${{ steps.buildozer.outputs.filename }}
