name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer Docker
      uses: artem-solovev/buildozer-action@v2
      with:
        work-dir: .
        buildozer-version: stable
        target: android
        command: buildozer android debug
        buildozer-params: ""

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Snake-By-Pasha-APK
        path: bin/*.apk
        retention-days: 30

    - name: Upload to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/*.apk
        asset_name: Snake-By-Pasha-${{ github.event.release.tag_name }}.apk
        asset_content_type: application/vnd.android.package-archive
