name: Build APK with Docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build APK with Docker
      run: |
        # Create a simple Dockerfile for buildozer
        cat > Dockerfile << 'EOF'
        FROM ubuntu:20.04
        
        # Set environment variables
        ENV DEBIAN_FRONTEND=noninteractive
        ENV ANDROID_HOME=/opt/android-sdk
        ENV ANDROID_SDK_ROOT=/opt/android-sdk
        ENV PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        # Install system dependencies
        RUN apt-get update && apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            python3-pip \
            libjpeg-dev \
            zlib1g-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            libncurses5-dev \
            libncursesw5-dev \
            xz-utils \
            tk-dev \
            libxml2-dev \
            libxmlsec1-dev \
            liblzma-dev \
            openjdk-8-jdk \
            git \
            unzip \
            wget \
            curl \
            cmake \
            ninja-build \
            pkg-config \
            && rm -rf /var/lib/apt/lists/*
        
        # Install Python dependencies
        RUN pip3 install --upgrade pip
        RUN pip3 install buildozer cython
        
        # Set working directory
        WORKDIR /app
        
        # Copy application files
        COPY . .
        
        # Initialize buildozer
        RUN buildozer init
        
        # Build APK
        RUN buildozer android debug
        EOF
        
        # Build Docker image
        docker build -t kivy-builder .
        
        # Run build in container
        docker run --rm -v $(pwd):/app kivy-builder
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: red-kivy-app
        path: bin/*.apk
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: build-logs
        path: .buildozer/
        retention-days: 7